Citizen.CreateThread(function()
    local blip = AddBlipForCoord(-440.52, -1705.64, 18.89)
    SetBlipSprite(blip, 318)
    -- SetBlipDisplay(blip, 4)
    SetBlipScale(blip, 0.8)
    SetBlipColour(blip, 5)
    SetBlipAsShortRange(blip, false)
    BeginTextCommandSetBlipName("STRING")
    AddTextComponentString("Lixeiro")
    EndTextCommandSetBlipName(blip)
end)